ALTER TABLE Phrase ADD SOURCE_URL VARCHAR(3000);
CREATE TABLE Phrase(
id INT NOT NULL AUTO_INCREMENT, 
PRIMARY KEY(id),
 WHO VARCHAR(3000),
 TIME_WHEN VARCHAR(3000), 
 DETAILS TEXT, 
 SOURCE VARCHAR(3000));
 ALTER TABLE Miscellaneous ADD SOURCE_URL VARCHAR(3000);
 drop table miscellaneous;
 CREATE TABLE Miscellaneous(
id INT NOT NULL AUTO_INCREMENT, 
PRIMARY KEY(id),
 DEFINITION_DETAILS1 TEXT, 
DEFINITION_DETAILS2 TEXT, 
DEFINITION_DETAILS3 TEXT,  
 SOURCE VARCHAR(3000));
 
 ALTER TABLE JOKE ADD SOURCE_URL VARCHAR(3000);
 CREATE TABLE JOKE(
id INT NOT NULL AUTO_INCREMENT, 
PRIMARY KEY(id),
 DETAILS TEXT, 
 SOURCE VARCHAR(3000));
 ALTER TABLE WORD ADD SOURCE_URL VARCHAR(3000);
  CREATE TABLE WORD(
id INT NOT NULL AUTO_INCREMENT, 
PRIMARY KEY(id),
WORD_ITSELF VARCHAR(3000),
 DEFINITION_DETAILS TEXT, 
 SOURCE VARCHAR(3000));
 
 CREATE TABLE RECIPE(
id INT NOT NULL AUTO_INCREMENT, 
PRIMARY KEY(id),
NAME VARCHAR(3000),
CREATOR_TRAINER VARCHAR(3000),
DEFINITION_DETAILS1 TEXT, 
DEFINITION_DETAILS2 TEXT, 
DEFINITION_DETAILS3 TEXT, 

 SOURCE VARCHAR(3000));
 
CREATE TABLE VIDEOTUBE(
id INT NOT NULL AUTO_INCREMENT, 
PRIMARY KEY(id),
NAME VARCHAR(3000),
DEFINITION_DETAILS1 TEXT, 
SOURCE_URL VARCHAR(3000),
 SOURCE VARCHAR(3000));
 
 CREATE TABLE VIDEOTUBE_KIDS(
id INT NOT NULL AUTO_INCREMENT, 
PRIMARY KEY(id),
NAME VARCHAR(3000),
DEFINITION_DETAILS1 TEXT, 
SOURCE_URL VARCHAR(3000),
 SOURCE VARCHAR(3000));
 
 INSERT into VIDEOTUBE_KIDS(name,definition_details1,source_url,source) values('third','third','www.youtube.com','youtube');

 
 CREATE TABLE PHOTOSTAND(
id INT NOT NULL AUTO_INCREMENT, 
PRIMARY KEY(id),
NAME VARCHAR(3000),
DEFINITION_DETAILS1 TEXT, 
SOURCE_URL VARCHAR(3000),
 SOURCE VARCHAR(3000));
 
 ALTER TABLE RECIPE ADD SOURCE_URL VARCHAR(3000);
 
 drop table IINTELNEWS;
CREATE TABLE IINTELNEWS(
id INT NOT NULL AUTO_INCREMENT, 
PRIMARY KEY(id),
HEADING VARCHAR(3000),
IMAGE_URL VARCHAR(3000),
DEFINITION_DETAILS TEXT,
SOURCE_URL VARCHAR(3000),
SOURCE VARCHAR(3000));
 
drop table IINTEL_RECORDS;
delete from IINTEL_RECORDS
CREATE TABLE IINTEL_RECORDS(
id INT NOT NULL AUTO_INCREMENT, 
PRIMARY KEY(id),
MISCELLANEOUS_ID INT ,
JOKE_ID INT ,
HEALTHTIP_ID INT ,
RECIPE_ID INT ,
VIDEOTUBE_ID INT ,
PHOTOSTAND_ID INT,
IINTELNEWS_ID INT,
IINTELDASHBOARD_ID INT);
delete from  IINTEL_RECORD_ITEM
drop table IINTEL_RECORD_ITEM
CREATE TABLE IINTEL_RECORD_ITEM(
id INT NOT NULL AUTO_INCREMENT, 
PRIMARY KEY(id),
IINTEL_RECORDS_ID INT NOT NULL, 
MISCELLANEOUS_ID INT ,
JOKE_ID INT ,
HEALTHTIP_ID INT ,
RECIPE_ID INT ,
VIDEOTUBE_ID INT ,
PHOTOSTAND_ID INT ,
IINTELNEWS_ID INT,
IINTELDASHBOARD_ID INT);

ALTER TABLE HEALTH_TIPS ADD SOURCE_URL VARCHAR(3000);
 CREATE TABLE HEALTH_TIPS(
id INT NOT NULL AUTO_INCREMENT, 
PRIMARY KEY(id),
 DEFINITION_DETAILS TEXT, 
 SOURCE VARCHAR(3000));
 
 CREATE TABLE IINTEL_DASHBOARD(
 id INT NOT NULL AUTO_INCREMENT,
 PRIMARY KEY(id),
 GOODEED VARCHAR(3000),
 FUNDEA VARCHAR(3000));
 